#include "mkv128_simd_avx512.h"

#if defined(__i386__) || defined(__x86_64__) \
    || defined(_M_IX86) || defined(_M_X64)
#define MKV128_AVX512_X86 1
#include <immintrin.h>
#else
#define MKV128_AVX512_X86 0
#endif

#if MKV128_AVX512_X86 && (defined(__GNUC__) || defined(__clang__))
#define MKV128_AVX512_IMPLEMENTED 1
#define MKV128_AVX512_TARGET \
    __attribute__((target("avx512f,avx512bw,avx512vbmi")))
#define MKV128_AVX512_GFNI_TARGET \
    __attribute__((target("avx512f,avx512bw,avx512vbmi,gfni")))

#include "PrecomputedTable128.h"

/*
 * S[x] = L4[x] >> 24.  Keeping S in four 64-byte ZMM registers lets
 * VPERMI2B substitute every byte of sixteen state words without gathers.
 * The entries are exactly those generated by tools/generate_tables.c.
 */
static const _Alignas(64) uint8_t mkv128_sbox[256] = {
    0x01u, 0x11u, 0x91u, 0xE1u, 0xD1u, 0xB1u, 0x71u, 0x61u, 0xF1u, 0x21u, 0xC1u, 0x51u, 0xA1u, 0x41u, 0x31u, 0x81u,
    0x00u, 0x10u, 0xE3u, 0x92u, 0xB5u, 0xD4u, 0x77u, 0x66u, 0x89u, 0x38u, 0xABu, 0x4Au, 0xCDu, 0x5Cu, 0x2Fu, 0xFEu,
    0x08u, 0x5Fu, 0x3Eu, 0xB0u, 0x1Cu, 0xC2u, 0x83u, 0xDDu, 0xE8u, 0xF6u, 0x47u, 0x79u, 0x95u, 0x2Bu, 0xAAu, 0x64u,
    0x0Fu, 0x48u, 0xD0u, 0x29u, 0xA3u, 0x1Au, 0xF2u, 0xBBu, 0x65u, 0xCCu, 0xE4u, 0x3Du, 0x57u, 0x7Eu, 0x86u, 0x9Fu,
    0x0Cu, 0x2Au, 0xF4u, 0x1Fu, 0x5Bu, 0x90u, 0xEEu, 0xC5u, 0x36u, 0x6Du, 0x73u, 0x88u, 0xBCu, 0xA7u, 0x49u, 0xD2u,
    0x0Au, 0x3Cu, 0x18u, 0x85u, 0xE0u, 0x4Du, 0x99u, 0xA4u, 0xB3u, 0x5Eu, 0xDAu, 0xC7u, 0x72u, 0xFFu, 0x6Bu, 0x26u,
    0x06u, 0x76u, 0xCFu, 0xA8u, 0x4Eu, 0x59u, 0x60u, 0x17u, 0xDCu, 0x9Bu, 0x32u, 0xF5u, 0x23u, 0x84u, 0xEDu, 0xBAu,
    0x07u, 0x67u, 0x2Du, 0x3Bu, 0xFAu, 0x8Cu, 0x16u, 0x70u, 0x54u, 0xA2u, 0x98u, 0xBEu, 0xEFu, 0xD9u, 0xC3u, 0x45u,
    0x0Eu, 0xA9u, 0x62u, 0x5Au, 0x27u, 0xBFu, 0x34u, 0x9Cu, 0xFDu, 0xD5u, 0x8Eu, 0xE6u, 0x1Bu, 0x43u, 0x78u, 0xC0u,
    0x03u, 0xB2u, 0x87u, 0xC4u, 0x9Du, 0x6Eu, 0x4Bu, 0xF8u, 0x7Au, 0xE9u, 0x2Cu, 0xAFu, 0xD6u, 0x15u, 0x50u, 0x33u,
    0x0Du, 0xFBu, 0x56u, 0xECu, 0x3Fu, 0x75u, 0xB8u, 0x42u, 0x1Eu, 0x24u, 0xC9u, 0x93u, 0x80u, 0x6Au, 0xD7u, 0xADu,
    0x04u, 0xE5u, 0xB9u, 0x7Du, 0x82u, 0xA6u, 0xCAu, 0x2Eu, 0x97u, 0x13u, 0x6Fu, 0xDBu, 0x44u, 0x30u, 0xFCu, 0x58u,
    0x0Bu, 0x8Du, 0x9Au, 0x46u, 0x74u, 0x28u, 0xDFu, 0x53u, 0xCBu, 0xB7u, 0xF0u, 0x6Cu, 0xAEu, 0xE2u, 0x35u, 0x19u,
    0x05u, 0x94u, 0x7Bu, 0xDEu, 0xC6u, 0xF3u, 0xACu, 0x39u, 0x4Fu, 0x8Au, 0x55u, 0x20u, 0x68u, 0xBDu, 0x12u, 0xE7u,
    0x02u, 0xD3u, 0xA5u, 0xF7u, 0x69u, 0xEBu, 0x5Du, 0x8Fu, 0x22u, 0x40u, 0xB6u, 0x14u, 0x3Au, 0xC8u, 0x9Eu, 0x7Cu,
    0x09u, 0xCEu, 0x4Cu, 0x63u, 0xD8u, 0x37u, 0x25u, 0xEAu, 0xA0u, 0x7Fu, 0x1Du, 0x52u, 0xF9u, 0x96u, 0xB4u, 0x8Bu,
};

MKV128_AVX512_TARGET
static inline __m512i mkv128_avx512_sub_mix(__m512i word)
{
    const __m512i byte_mask = _mm512_set1_epi32(0xff);
    const __m512i part0 = _mm512_i32gather_epi32(
        _mm512_srli_epi32(word, 24), L0, 4);
    const __m512i part1 = _mm512_i32gather_epi32(
        _mm512_and_si512(_mm512_srli_epi32(word, 16), byte_mask), L1, 4);
    const __m512i part2 = _mm512_i32gather_epi32(
        _mm512_and_si512(_mm512_srli_epi32(word, 8), byte_mask), L2, 4);
    const __m512i part3 = _mm512_i32gather_epi32(
        _mm512_and_si512(word, byte_mask), L3, 4);

    return _mm512_xor_si512(
        _mm512_ternarylogic_epi32(part0, part1, part2, 0x96), part3);
}

MKV128_AVX512_TARGET
static inline __m512i mkv128_avx512_sub_word(__m512i word,
                                              __m512i table0,
                                              __m512i table1,
                                              __m512i table2,
                                              __m512i table3)
{
    const __m512i lower = _mm512_permutex2var_epi8(table0, word, table1);
    const __m512i upper = _mm512_permutex2var_epi8(table2, word, table3);
    const __mmask64 high_half = _mm512_movepi8_mask(word);

    return _mm512_mask_blend_epi8(high_half, lower, upper);
}

MKV128_AVX512_TARGET
static void mkv128_encrypt_avx512_batches(const mkv128_ctx *ctx,
                                          const uint8_t *input,
                                          uint8_t *output,
                                          size_t vector_blocks)
{
    const __m512i block_offsets = _mm512_setr_epi32(
        0, 16, 32, 48, 64, 80, 96, 112,
        128, 144, 160, 176, 192, 208, 224, 240);
    const __m512i byte_swap = _mm512_setr_epi32(
        0x00010203, 0x04050607, 0x08090a0b, 0x0c0d0e0f,
        0x00010203, 0x04050607, 0x08090a0b, 0x0c0d0e0f,
        0x00010203, 0x04050607, 0x08090a0b, 0x0c0d0e0f,
        0x00010203, 0x04050607, 0x08090a0b, 0x0c0d0e0f);
    const __m512i sbox0 = _mm512_load_si512((const void *)(mkv128_sbox + 0));
    const __m512i sbox1 = _mm512_load_si512((const void *)(mkv128_sbox + 64));
    const __m512i sbox2 = _mm512_load_si512((const void *)(mkv128_sbox + 128));
    const __m512i sbox3 = _mm512_load_si512((const void *)(mkv128_sbox + 192));

    while (vector_blocks != 0u) {
        __m512i state0 = _mm512_shuffle_epi8(
            _mm512_i32gather_epi32(block_offsets, input + 0u, 1), byte_swap);
        __m512i state1 = _mm512_shuffle_epi8(
            _mm512_i32gather_epi32(block_offsets, input + 4u, 1), byte_swap);
        __m512i state2 = _mm512_shuffle_epi8(
            _mm512_i32gather_epi32(block_offsets, input + 8u, 1), byte_swap);
        __m512i state3 = _mm512_shuffle_epi8(
            _mm512_i32gather_epi32(block_offsets, input + 12u, 1), byte_swap);
        unsigned round;

        for (round = 0u; round < MKV128_ROUNDS; ++round) {
            const uint32_t *round_key = ctx->round_keys + 8u * round;
            const __m512i word0 = mkv128_avx512_sub_word(
                _mm512_xor_si512(
                    mkv128_avx512_sub_mix(_mm512_xor_si512(
                        state0, _mm512_set1_epi32((int)round_key[0]))),
                    _mm512_set1_epi32((int)round_key[4])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i word1 = mkv128_avx512_sub_word(
                _mm512_xor_si512(
                    mkv128_avx512_sub_mix(_mm512_xor_si512(
                        state1, _mm512_set1_epi32((int)round_key[1]))),
                    _mm512_set1_epi32((int)round_key[5])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i word2 = mkv128_avx512_sub_word(
                _mm512_xor_si512(
                    mkv128_avx512_sub_mix(_mm512_xor_si512(
                        state2, _mm512_set1_epi32((int)round_key[2]))),
                    _mm512_set1_epi32((int)round_key[6])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i word3 = mkv128_avx512_sub_word(
                _mm512_xor_si512(
                    mkv128_avx512_sub_mix(_mm512_xor_si512(
                        state3, _mm512_set1_epi32((int)round_key[3]))),
                    _mm512_set1_epi32((int)round_key[7])),
                sbox0, sbox1, sbox2, sbox3);

            state0 = _mm512_ternarylogic_epi32(word1, word2, word3, 0x96);
            state1 = _mm512_ternarylogic_epi32(word0, word2, word3, 0x96);
            state2 = _mm512_ternarylogic_epi32(word0, word1, word3, 0x96);
            state3 = _mm512_ternarylogic_epi32(word0, word1, word2, 0x96);
        }

        state0 = _mm512_shuffle_epi8(_mm512_xor_si512(
            state0, _mm512_set1_epi32((int)ctx->round_keys[48])), byte_swap);
        state1 = _mm512_shuffle_epi8(_mm512_xor_si512(
            state1, _mm512_set1_epi32((int)ctx->round_keys[49])), byte_swap);
        state2 = _mm512_shuffle_epi8(_mm512_xor_si512(
            state2, _mm512_set1_epi32((int)ctx->round_keys[50])), byte_swap);
        state3 = _mm512_shuffle_epi8(_mm512_xor_si512(
            state3, _mm512_set1_epi32((int)ctx->round_keys[51])), byte_swap);

        _mm512_i32scatter_epi32(output + 0u, block_offsets, state0, 1);
        _mm512_i32scatter_epi32(output + 4u, block_offsets, state1, 1);
        _mm512_i32scatter_epi32(output + 8u, block_offsets, state2, 1);
        _mm512_i32scatter_epi32(output + 12u, block_offsets, state3, 1);

        input += 16u * MKV128_BLOCK_BYTES;
        output += 16u * MKV128_BLOCK_BYTES;
        vector_blocks -= 16u;
    }
}

/*
 * The GFNI affine operation is NOT its AES-field multiplication operation.
 * These binary matrices instead encode multiplication modulo MKV's own
 * x^8 + x^5 + x^3 + x + 1 polynomial (0x12B).  For output bit i, byte
 * 7-i of the 64-bit matrix contains the input bits contributing to bit i.
 * Every matrix was checked for all 256 possible byte inputs against the
 * polynomial-0x12B reference implementation.
 */
#define MKV128_GFNI_MUL2  UINT64_C(0x8081028408902040)
#define MKV128_GFNI_MUL4  UINT64_C(0x40C0814284489020)
#define MKV128_GFNI_MUL8  UINT64_C(0x2060C0A142A44890)
#define MKV128_GFNI_MUL16 UINT64_C(0x90B06050A1D2A448)

/* Deinterleave sixteen 16-byte blocks into four 64-byte word columns. */
static const _Alignas(64) uint8_t mkv128_column01_index[64] = {
      0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,  56,  60,
     64,  68,  72,  76,  80,  84,  88,  92,  96, 100, 104, 108, 112, 116, 120, 124,
      1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,  53,  57,  61,
     65,  69,  73,  77,  81,  85,  89,  93,  97, 101, 105, 109, 113, 117, 121, 125,
};
static const _Alignas(64) uint8_t mkv128_column23_index[64] = {
      2,   6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,  58,  62,
     66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106, 110, 114, 118, 122, 126,
      3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,  55,  59,  63,
     67,  71,  75,  79,  83,  87,  91,  95,  99, 103, 107, 111, 115, 119, 123, 127,
};
static const _Alignas(64) uint8_t mkv128_low_halves_index[64] = {
      0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
     16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
     64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
     80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
};
static const _Alignas(64) uint8_t mkv128_high_halves_index[64] = {
     32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
     48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
     96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
    112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
};
static const _Alignas(64) uint8_t mkv128_interleave0_index[64] = {
      0,  32,  64,  96,   1,  33,  65,  97,   2,  34,  66,  98,   3,  35,  67,  99,
      4,  36,  68, 100,   5,  37,  69, 101,   6,  38,  70, 102,   7,  39,  71, 103,
      8,  40,  72, 104,   9,  41,  73, 105,  10,  42,  74, 106,  11,  43,  75, 107,
     12,  44,  76, 108,  13,  45,  77, 109,  14,  46,  78, 110,  15,  47,  79, 111,
};
static const _Alignas(64) uint8_t mkv128_interleave1_index[64] = {
     16,  48,  80, 112,  17,  49,  81, 113,  18,  50,  82, 114,  19,  51,  83, 115,
     20,  52,  84, 116,  21,  53,  85, 117,  22,  54,  86, 118,  23,  55,  87, 119,
     24,  56,  88, 120,  25,  57,  89, 121,  26,  58,  90, 122,  27,  59,  91, 123,
     28,  60,  92, 124,  29,  61,  93, 125,  30,  62,  94, 126,  31,  63,  95, 127,
};

static inline uint32_t mkv128_pack_key_column(const uint32_t key[4],
                                               unsigned column)
{
    const unsigned shift = 24u - 8u * column;

    return ((key[0] >> shift) & 0xffu)
         | (((key[1] >> shift) & 0xffu) << 8u)
         | (((key[2] >> shift) & 0xffu) << 16u)
         | (((key[3] >> shift) & 0xffu) << 24u);
}

MKV128_AVX512_GFNI_TARGET
static inline __m512i mkv128_avx512_mix_state_words(__m512i column)
{
    const __m512i swap_neighbors = _mm512_setr_epi32(
        0x02030001, 0x06070405, 0x0a0b0809, 0x0e0f0c0d,
        0x02030001, 0x06070405, 0x0a0b0809, 0x0e0f0c0d,
        0x02030001, 0x06070405, 0x0a0b0809, 0x0e0f0c0d,
        0x02030001, 0x06070405, 0x0a0b0809, 0x0e0f0c0d);
    const __m512i swap_pairs = _mm512_setr_epi32(
        0x01000302, 0x05040706, 0x09080b0a, 0x0d0c0f0e,
        0x01000302, 0x05040706, 0x09080b0a, 0x0d0c0f0e,
        0x01000302, 0x05040706, 0x09080b0a, 0x0d0c0f0e,
        0x01000302, 0x05040706, 0x09080b0a, 0x0d0c0f0e);
    const __m512i neighbor = _mm512_shuffle_epi8(column, swap_neighbors);
    const __m512i pair = _mm512_xor_si512(column, neighbor);

    return _mm512_xor_si512(neighbor, _mm512_shuffle_epi8(pair, swap_pairs));
}

MKV128_AVX512_GFNI_TARGET
static void mkv128_encrypt_avx512_gfni_batches(const mkv128_ctx *ctx,
                                               const uint8_t *input,
                                               uint8_t *output,
                                               size_t vector_blocks)
{
    const __m512i index01 = _mm512_load_si512(mkv128_column01_index);
    const __m512i index23 = _mm512_load_si512(mkv128_column23_index);
    const __m512i index_low = _mm512_load_si512(mkv128_low_halves_index);
    const __m512i index_high = _mm512_load_si512(mkv128_high_halves_index);
    const __m512i index_out0 = _mm512_load_si512(mkv128_interleave0_index);
    const __m512i index_out1 = _mm512_load_si512(mkv128_interleave1_index);
    const __m512i sbox0 = _mm512_load_si512((const void *)(mkv128_sbox + 0));
    const __m512i sbox1 = _mm512_load_si512((const void *)(mkv128_sbox + 64));
    const __m512i sbox2 = _mm512_load_si512((const void *)(mkv128_sbox + 128));
    const __m512i sbox3 = _mm512_load_si512((const void *)(mkv128_sbox + 192));
    const __m512i matrix2 = _mm512_set1_epi64((int64_t)MKV128_GFNI_MUL2);
    const __m512i matrix4 = _mm512_set1_epi64((int64_t)MKV128_GFNI_MUL4);
    const __m512i matrix8 = _mm512_set1_epi64((int64_t)MKV128_GFNI_MUL8);
    const __m512i matrix16 = _mm512_set1_epi64((int64_t)MKV128_GFNI_MUL16);
    uint32_t packed_keys[MKV128_KEY_WORDS];
    unsigned group;

    for (group = 0u; group < MKV128_KEY_WORDS / 4u; ++group) {
        unsigned column;

        for (column = 0u; column < 4u; ++column) {
            packed_keys[4u * group + column] =
                mkv128_pack_key_column(ctx->round_keys + 4u * group, column);
        }
    }

    while (vector_blocks != 0u) {
        const __m512i input0 = _mm512_loadu_si512((const void *)(input + 0u));
        const __m512i input1 = _mm512_loadu_si512((const void *)(input + 64u));
        const __m512i input2 = _mm512_loadu_si512((const void *)(input + 128u));
        const __m512i input3 = _mm512_loadu_si512((const void *)(input + 192u));
        const __m512i first01 = _mm512_permutex2var_epi8(input0, index01, input1);
        const __m512i first23 = _mm512_permutex2var_epi8(input0, index23, input1);
        const __m512i last01 = _mm512_permutex2var_epi8(input2, index01, input3);
        const __m512i last23 = _mm512_permutex2var_epi8(input2, index23, input3);
        __m512i state0 = _mm512_permutex2var_epi8(first01, index_low, last01);
        __m512i state1 = _mm512_permutex2var_epi8(first01, index_high, last01);
        __m512i state2 = _mm512_permutex2var_epi8(first23, index_low, last23);
        __m512i state3 = _mm512_permutex2var_epi8(first23, index_high, last23);
        unsigned round;

        for (round = 0u; round < MKV128_ROUNDS; ++round) {
            const uint32_t *round_key = packed_keys + 8u * round;
            const __m512i a = mkv128_avx512_sub_word(
                _mm512_xor_si512(state0, _mm512_set1_epi32((int)round_key[0])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i b = mkv128_avx512_sub_word(
                _mm512_xor_si512(state1, _mm512_set1_epi32((int)round_key[1])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i c = mkv128_avx512_sub_word(
                _mm512_xor_si512(state2, _mm512_set1_epi32((int)round_key[2])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i d = mkv128_avx512_sub_word(
                _mm512_xor_si512(state3, _mm512_set1_epi32((int)round_key[3])),
                sbox0, sbox1, sbox2, sbox3);
            const __m512i ab = _mm512_xor_si512(a, b);
            const __m512i ad = _mm512_xor_si512(a, d);
            const __m512i bc = _mm512_xor_si512(b, c);
            const __m512i bd = _mm512_xor_si512(b, d);
            const __m512i bc2 = _mm512_gf2p8affine_epi64_epi8(bc, matrix2, 0);

            /*
             * Factor the original MKV matrix over GF(2^8):
             *
             * [01 02 01 03]   mix0 = a+c+d       + 2(b+d)
             * [03 07 01 04]   mix1 = a+b+c       + 2(a+b) + 4(b+d)
             * [04 0B 03 0D]   mix2 = b+c+d       + 2(b+c) + 4(a+d) + 8(b+d)
             * [0D 1E 06 14]   mix3 = a + 2(b+c)  + 4(a+b+c+d)
             *                                      + 8(a+b) + 16(b+d).
             *
             * The common term 2(b+c) is reused, leaving nine affine
             * instructions for all 64 state words in sixteen blocks.
             */
            const __m512i mix0 = _mm512_ternarylogic_epi32(
                _mm512_ternarylogic_epi32(a, c, d, 0x96),
                _mm512_gf2p8affine_epi64_epi8(bd, matrix2, 0),
                _mm512_set1_epi32((int)round_key[4]), 0x96);
            const __m512i mix1 = _mm512_ternarylogic_epi32(
                _mm512_ternarylogic_epi32(a, b, c, 0x96),
                _mm512_gf2p8affine_epi64_epi8(ab, matrix2, 0),
                _mm512_ternarylogic_epi32(
                    _mm512_gf2p8affine_epi64_epi8(bd, matrix4, 0),
                    _mm512_set1_epi32((int)round_key[5]),
                    _mm512_setzero_si512(), 0x96), 0x96);
            const __m512i mix2 = _mm512_ternarylogic_epi32(
                _mm512_ternarylogic_epi32(b, c, d, 0x96), bc2,
                _mm512_ternarylogic_epi32(
                    _mm512_gf2p8affine_epi64_epi8(ad, matrix4, 0),
                    _mm512_gf2p8affine_epi64_epi8(bd, matrix8, 0),
                    _mm512_set1_epi32((int)round_key[6]), 0x96), 0x96);
            const __m512i mix3 = _mm512_ternarylogic_epi32(
                _mm512_ternarylogic_epi32(a, bc2,
                    _mm512_gf2p8affine_epi64_epi8(
                        _mm512_xor_si512(ab, _mm512_xor_si512(c, d)),
                        matrix4, 0), 0x96),
                _mm512_gf2p8affine_epi64_epi8(ab, matrix8, 0),
                _mm512_ternarylogic_epi32(
                    _mm512_gf2p8affine_epi64_epi8(bd, matrix16, 0),
                    _mm512_set1_epi32((int)round_key[7]),
                    _mm512_setzero_si512(), 0x96), 0x96);

            state0 = mkv128_avx512_mix_state_words(mkv128_avx512_sub_word(
                mix0, sbox0, sbox1, sbox2, sbox3));
            state1 = mkv128_avx512_mix_state_words(mkv128_avx512_sub_word(
                mix1, sbox0, sbox1, sbox2, sbox3));
            state2 = mkv128_avx512_mix_state_words(mkv128_avx512_sub_word(
                mix2, sbox0, sbox1, sbox2, sbox3));
            state3 = mkv128_avx512_mix_state_words(mkv128_avx512_sub_word(
                mix3, sbox0, sbox1, sbox2, sbox3));
        }

        state0 = _mm512_xor_si512(
            state0, _mm512_set1_epi32((int)packed_keys[48]));
        state1 = _mm512_xor_si512(
            state1, _mm512_set1_epi32((int)packed_keys[49]));
        state2 = _mm512_xor_si512(
            state2, _mm512_set1_epi32((int)packed_keys[50]));
        state3 = _mm512_xor_si512(
            state3, _mm512_set1_epi32((int)packed_keys[51]));

        {
            const __m512i out_first01 =
                _mm512_permutex2var_epi8(state0, index_low, state1);
            const __m512i out_last01 =
                _mm512_permutex2var_epi8(state0, index_high, state1);
            const __m512i out_first23 =
                _mm512_permutex2var_epi8(state2, index_low, state3);
            const __m512i out_last23 =
                _mm512_permutex2var_epi8(state2, index_high, state3);

            _mm512_storeu_si512((void *)(output + 0u),
                _mm512_permutex2var_epi8(out_first01, index_out0, out_first23));
            _mm512_storeu_si512((void *)(output + 64u),
                _mm512_permutex2var_epi8(out_first01, index_out1, out_first23));
            _mm512_storeu_si512((void *)(output + 128u),
                _mm512_permutex2var_epi8(out_last01, index_out0, out_last23));
            _mm512_storeu_si512((void *)(output + 192u),
                _mm512_permutex2var_epi8(out_last01, index_out1, out_last23));
        }

        input += 16u * MKV128_BLOCK_BYTES;
        output += 16u * MKV128_BLOCK_BYTES;
        vector_blocks -= 16u;
    }
}

#else
#define MKV128_AVX512_IMPLEMENTED 0
#endif

int mkv128_avx512_available(void)
{
#if MKV128_AVX512_IMPLEMENTED
    return __builtin_cpu_supports("avx512f")
        && __builtin_cpu_supports("avx512bw")
        && __builtin_cpu_supports("avx512vbmi");
#else
    return 0;
#endif
}

int mkv128_avx512_gfni_available(void)
{
#if MKV128_AVX512_IMPLEMENTED
    return mkv128_avx512_available() && __builtin_cpu_supports("gfni");
#else
    return 0;
#endif
}

void mkv128_encrypt_blocks_avx512(const mkv128_ctx *ctx,
                                  const uint8_t *input,
                                  uint8_t *output,
                                  size_t block_count)
{
#if MKV128_AVX512_IMPLEMENTED
    const size_t vector_blocks = block_count & ~(size_t)15u;

    if (vector_blocks != 0u && mkv128_avx512_available()) {
        if (__builtin_cpu_supports("gfni")) {
            mkv128_encrypt_avx512_gfni_batches(ctx, input, output,
                                               vector_blocks);
        } else {
            mkv128_encrypt_avx512_batches(ctx, input, output, vector_blocks);
        }
        input += vector_blocks * MKV128_BLOCK_BYTES;
        output += vector_blocks * MKV128_BLOCK_BYTES;
        block_count -= vector_blocks;
    }
#endif

    while (block_count != 0u) {
        mkv128_encrypt_block(ctx, input, output);
        input += MKV128_BLOCK_BYTES;
        output += MKV128_BLOCK_BYTES;
        --block_count;
    }
}
